
pipeline {
    environment{
            registry = "test"
            registryCredential = "test"
    }
    agent any

    stages {
        stage("Parallel Testing"){
            parallel    {
                stage('Build') {
                    steps {
                        sh 'chmod +x gradlew'
                        sh './gradlew clean build'
                    }
                }
                stage('Unit Test') {
                    steps {
                        echo "Finished Unit Testing"
                    }
                }
                stage('Integration Test') {
                    steps {
                        echo "Finished Integration Testing"
                    }
                }
                stage('Performance Test') {
                    steps {
                        echo "Finished Performance Testing"
                    }
                }
                stage('Code Report Generation'){
                    steps {
                        echo "Code Report Generated"
                    }
                }
            }
        }
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t kirkensgaardexamples/generated-projects:@projectName@ .'
            }
        }
        stage('Push Image to Docker Hub'){
            steps{
                sh 'docker login --username=kirkensgaardexamples --password=Right55HDuke'
                sh 'docker push kirkensgaardexamples/generated-projects:@projectName@'
            }
        }
    }
}